title = "Alpaca Sample Driver (Rotator)"

[network]
ip_address = '192.168.0.42'
mc_address = '192.168.0.255'
port = 5555

[server]
location = 'Alvord Desert'
verbose_driver_exceptions = true

[device]
can_reverse = true
step_size = 1.0
steps_per_sec = 6

[logging]
log_level = 'INFO'
log_to_stdout = false
max_size_mb = 5
num_keep_logs = 10
