#! /usr/bin/env python
# -*- coding: utf-8 -*-
#
# -----------------------------------------------------------------------------
# observingconditions.py - Alpaca API responders for Observingconditions
#
# Author:   Gunter Georgi <ggtux@gmx.net> (geo)
#
# -----------------------------------------------------------------------------
# Edit History:
#   Generated by Python Interface Generator for AlpycaDevice
#
# 25.Feb. 2025 geo Initial edit
# 01. Mrz 2025 geo partiell arbeitsfähig
# 11. Mrz 2025 geo Verbesserung der raindetection
# 16. Mrz.2025 geo all functions are running but optimization required
# 20. Mrz.2025 geo exp. regression for cloudcover programmed - working



from falcon import Request, Response, HTTPBadRequest, before
from logging import Logger
from shr import PropertyResponse, MethodResponse, PreProcessRequest, \
                StateValue, get_request_field, to_bool
from exceptions import *        # Nothing but exception classes
import smbus2
import board # installiere Adafruit-Board - wichtig!
import busio
import adafruit_tsl2591
import adafruit_mlx90614
from datetime import datetime
import threading
import json
import os
from time import sleep
from micropython import const
from numpy import sign
from math import log10,log,exp,pow
import requests
from w1thermsensor import W1ThermSensor, Unit
import RPi.GPIO as GPIO
import time


# bedarf pip install rpi.lgpio!!


# Global variables

rain_pin=23
rain_vol = 0.
rain_pin_counter=0
last_drop_time=time.time()
Tobj = None  # Globale Variable für Objekt-Temperatur
SENSOR_JSON_PATH = "/home/geo/Arbeitsplatz/Weatherdata/sensor-readings.json"
print ("Starzeit: ", last_drop_time)
def write_sensor_json():
    global Tobj, rain_vol, rain_pin_counter
    while True:
        try:
            # Zeitstempel
            timestamp = datetime.utcnow().isoformat()
            # Werte auslesen (Tobj wird im cloudcover-Handler gesetzt, rain_vol im rainrate-Handler)
            # Fallback: Wenn Tobj None, versuche aktuellen Wert zu lesen
            if Tobj is None:
                try:
                    i2c = busio.I2C(board.SCL, board.SDA)
                    mlx = adafruit_mlx90614.MLX90614(i2c)
                    current_Tobj = mlx.object_temperature
                except Exception:
                    current_Tobj = None
            else:
                current_Tobj = Tobj

            # brightness.lux und tsl.lux auslesen
            try:
                i2c2 = busio.I2C(board.SCL, board.SDA)
                brightness = adafruit_tsl2591.TSL2591(i2c2)
                brightness_lux = brightness.lux
            except Exception:
                brightness_lux = None

            try:
                i2c3 = busio.I2C(board.SCL, board.SDA)
                tsl = adafruit_tsl2591.TSL2591(i2c3)
                tsl_lux = tsl.lux
            except Exception:
                tsl_lux = None

            data = {
                "timestamp": timestamp,
                "Tobj": current_Tobj,
                "rain_vol": rain_vol,
                "rain_pin_counter": rain_pin_counter,
                "brightness_lux": brightness_lux,
                "tsl_lux": tsl_lux
            }
            # Datei schreiben (append, falls Datei existiert, sonst neu)
            if os.path.exists(SENSOR_JSON_PATH):
                with open(SENSOR_JSON_PATH, "r+") as f:
                    try:
                        arr = json.load(f)
                        if not isinstance(arr, list):
                            arr = []
                    except Exception:
                        arr = []
                    arr.append(data)
                    f.seek(0)
                    json.dump(arr, f, indent=2)
                    f.truncate()
            else:
                with open(SENSOR_JSON_PATH, "w") as f:
                    json.dump([data], f, indent=2)
        except Exception as e:
            print(f"Fehler beim Schreiben der Sensorwerte: {e}")
        sleep(300)  # 5 Minuten

# Starte Hintergrund-Thread beim Modulimport
threading.Thread(target=write_sensor_json, daemon=True).start()


# RG-11 Regensensor ab Zeile 360
GPIO.setmode(GPIO.BCM)
GPIO.setup(rain_pin, GPIO.IN,pull_up_down=GPIO.PUD_UP)

# Globale callback Funktion für RG-11
def rain_pin_handler(pin):
    global rain_pin, rain_pin_counter, last_drop_time
    rain_pin_counter +=1
    last_drop_time=time.time()
    print("IRQ: letzter Tropfen um: ", last_drop_time)
       
    
    
GPIO.add_event_detect(23, GPIO.BOTH,rain_pin_handler) 

# Internal constants:
_MLX90614_I2CADDR = const(0x5A)
_MLX90614_TA = const(0x06)
_MLX90614_TOBJ1 = const(0x07)
_MLX90614_CONFIG = const(0x25)

# ----------------------
# MULTI-INSTANCE SUPPORT
# ----------------------
# If this is > 0 then it means that multiple devices of this type are supported.
# Each responder on_get() and on_put() is called with a devnum parameter to indicate
# which instance of the device (0-based) is being called by the client. Leave this
# set to 0 for the simple case of controlling only one instance of this device type.
#
maxdev = 0                      # Single instance
is_conn = True
# -----------
# DEVICE INFO
# -----------
# Static metadata not subject to configuration changes
## EDIT FOR YOUR DEVICE ##
class ObservingconditionsMetadata:
    """ Metadata describing the Observingconditions Device. Edit for your device"""
    Name = 'ObsBedingungen'
    Version = 'V001'
    Description = ' Wetter und SeeingSensoren'
    DeviceType = 'Observingconditions'
    DeviceID = '9243a204-804f-4598-8c1c-24465d1dc253' # https://guidgenerator.com/online-guid-generator.aspx
    Info = 'Alpaca  Device\nImplements IObservingconditions\nASCOM Initiative'
    MaxDeviceNumber = maxdev
    InterfaceVersion = "IObservingconditionsV001"       # IObservingconditionsVxxx


# --------------------
# RESOURCE CONTROLLERS
# --------------------

@before(PreProcessRequest(maxdev))
class action:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class commandblind:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class commandbool:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class commandstring:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class connect:
    def on_put(self, req: Request, resp: Response, devnum: int):
        try:
            # ------------------------
            ### CONNECT THE DEVICE ###
            # ------------------------
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Observingconditions.Connect failed', ex)).json

@before(PreProcessRequest(maxdev))
class connected:
    def on_get(self, req: Request, resp: Response, devnum: int):
        try:
            # -------------------------------------
            is_conn  = True ### READ CONN STATE ###
            # -------------------------------------
            resp.text = PropertyResponse(is_conn, req).json
        except Exception as ex:
            resp.text = MethodResponse(req, DriverException(0x500, 'Observingconditions.Connected failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        conn_str = get_request_field('Connected', req)
        conn = to_bool(conn_str)              # Raises 400 Bad Request if str to bool fails

        try:
            # --------------------------------------
            ### CONNECT OR DISCONNECT THE DEVICE ###
            # --------------------------------------
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req, # Put is actually like a method :-(
                            DriverException(0x500, 'Observingconditions.Connected failed', ex)).json

@before(PreProcessRequest(maxdev))
class connecting:
    def on_get(self, req: Request, resp: Response, devnum: int):
        try:
            # ------------------------------
            val = True
            # ------------------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Observingconditions.Connecting failed', ex)).json

@before(PreProcessRequest(maxdev))
class description:
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(ObservingconditionsMetadata.Description, req).json

@before(PreProcessRequest(maxdev))
class devicestate:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not is_conn: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        try:
            # ----------------------
            val = []
            # val.append(StateValue('## NAME ##', ## GET VAL ##))
            # Repeat for each of the operational states per the device spec
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'observingconditions.Devicestate failed', ex)).json


class disconnect:
    def on_put(self, req: Request, resp: Response, devnum: int):
        try:
            # ---------------------------
            is_conn = False ### DISCONNECT THE DEVICE ###
            # ---------------------------
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Observingconditions.Disconnect failed', ex)).json

@before(PreProcessRequest(maxdev))
class driverinfo:
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(ObservingconditionsMetadata.Info, req).json

@before(PreProcessRequest(maxdev))
class interfaceversion:
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(ObservingconditionsMetadata.InterfaceVersion, req).json

@before(PreProcessRequest(maxdev))
class driverversion():
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(ObservingconditionsMetadata.Version, req).json

@before(PreProcessRequest(maxdev))
class name():
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(ObservingconditionsMetadata.Name, req).json

@before(PreProcessRequest(maxdev))
class supportedactions:
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse([], req).json  # Not PropertyNotImplemented

@before(PreProcessRequest(maxdev))
class averageperiod:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not is_conn: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            val = 3 ## GET PROPERTY ##
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Observingconditions.Averageperiod failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not is_conn: ## IS DEV CONNECTED ##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        averageperiodstr = get_request_field('AveragePeriod', req)      # Raises 400 bad request if missing
        try:
            averageperiod = float(averageperiodstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'AveragePeriod {averageperiodstr} not a valid number.')).json
            return
        ### RANGE CHECK AS NEEDED ###  # Raise Alpaca InvalidValueException with details!
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Observingconditions.Averageperiod failed', ex)).json

@before(PreProcessRequest(maxdev))
class cloudcover:


    def on_get(self, req: Request, resp: Response, devnum: int):
        if not is_conn: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            i2c = busio.I2C(board.SCL, board.SDA)
            K1 = 50.
            K2 = 110.
            K3 = 4.
            K4 = 100.
            K5 = 100.
            K6 = 10.
            K7 = 100.
            mlx = adafruit_mlx90614.MLX90614(i2c)
            Tamb=mlx.ambient_temperature -10
            global Tobj
            Tobj=mlx.object_temperature
            if abs((K2 / 10. - Tamb)) < 1:
               T67 = sign(K6) * sign(Tamb - K2 / 10.) * abs((K2 / 10. - Tamb))
            else:
               T67 = K6 / 10. * sign(Tamb - K2 / 10.) * (log(abs((K2 / 10. - Tamb))) / log(10.) + K7 / 100.)
            
            Td = (K1 / 100.) * (Tamb - K2 / 10.) + (K3 / 100.) * pow(exp(K4 / 1000. * Tamb), (K5 / 100.)) + T67
            Tsky=Tobj-Td
            #exponentielle Anpassungsgleichung:
            val= 16.*exp(0.346574*Tsky)
            #print("Tsky; Tamb; Td = ", Tsky,Tamb, Td)
            #val=12.5*Tsky+60
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Observingconditions.Cloudcover failed', ex)).json


@before(PreProcessRequest(maxdev))
class rainrate:
    
    def on_get(self, req: Request, resp: Response, devnum: int):
        global rain_pin_counter, rain_timer,rain_start, rain_vol
                   
        if not is_conn: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            #print("akt. Zeit im loop: ",time.time())
            if ((time.time()-last_drop_time)>1800):
                rain_pin_counter =0
            global rain_vol
            rain_vol=round(rain_pin_counter*0.2,2)
            #print("Regenvolumen: ",rain_vol)
            resp.text = PropertyResponse(rain_vol, req).json
            time.sleep(0.01)
        except Exception as ex:
                resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Observingconditions.Rainrate failed', ex)).json

@before(PreProcessRequest(maxdev))
class skybrightness:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not is_conn: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            i2c = busio.I2C(board.SCL, board.SDA)
            brightness = adafruit_tsl2591.TSL2591(i2c)
            val=brightness.lux
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Observingconditions.Skybrightness failed', ex)).json

@before(PreProcessRequest(maxdev))
class skyquality:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not is_conn: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            # ----------------------
            i2c = busio.I2C(board.SCL, board.SDA)
            tsl=adafruit_tsl2591.TSL2591(i2c)
            calFac = 5.7
            val = calFac + (log((tsl.lux / 108000.0), 10) / -0.4)
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Observingconditions.Skyquality failed', ex)).json

@before(PreProcessRequest(maxdev))
class skytemperature:

#while True:
#	print("Ambent Temp: ", mlx.ambient_temperature)
#	print("Object Temp: ", mlx.object_temperature)
#	time.sleep(1)

     def on_get(self, req: Request, resp: Response, devnum: int):
        if not is_conn: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            #i2c = board.I2C()
            i2c = busio.I2C(board.SCL, board.SDA)
            mlx = adafruit_mlx90614.MLX90614(i2c)
            val = mlx.object_temperature
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Observingconditions.Skytemperature failed', ex)).json
#
# @before(PreProcessRequest(maxdev))
# class starfwhm:
#
#     def on_get(self, req: Request, resp: Response, devnum: int):
#         if not is_conn: ##IS DEV CONNECTED##:
#             resp.text = PropertyResponse(None, req,
#                             NotConnectedException()).json
#             return
#
#         try:
#             # ----------------------
#             val = ## GET PROPERTY ##
#             # ----------------------
#             resp.text = PropertyResponse(val, req).json
#         except Exception as ex:
#             resp.text = PropertyResponse(None, req,
#                             DriverException(0x500, 'Observingconditions.Starfwhm failed', ex)).json
#
@before(PreProcessRequest(maxdev))
class temperature:

     def on_get(self, req: Request, resp: Response, devnum: int):
         if not is_conn: ##IS DEV CONNECTED##:
             resp.text = PropertyResponse(None, req,
                             NotConnectedException()).json
             return

         try:
             Innentemp = W1ThermSensor()
             caminside = Innentemp.get_temperature()
             resp.text = PropertyResponse(caminside, req).json
         except Exception as ex:
             resp.text = PropertyResponse(None, req,
                             DriverException(0x500, 'Observingconditions.Dewpoint failed', ex)).json

@before(PreProcessRequest(maxdev))
class refresh:

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not is_conn: ## IS DEV CONNECTED ##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Observingconditions.Refresh failed', ex)).json

@before(PreProcessRequest(maxdev))
class sensordescription:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not is_conn: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        sensorname = get_request_field('SensorName', req)         # Raises 400 bad request if missing
        ### INTEPRET AS NEEDED OR FAIL ###  # Raise Alpaca InvalidValueException with details!
        try:
            # ----------------------
            val = 1 ## GET PROPERTY ##
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Observingconditions.Sensordescription failed', ex)).json

@before(PreProcessRequest(maxdev))
class timesincelastupdate:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not is_conn: ##IS DEV CONNECTED##:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        sensorname = get_request_field('SensorName', req)         # Raises 400 bad request if missing
        ### INTEPRET AS NEEDED OR FAIL ###  # Raise Alpaca InvalidValueException with details!
        try:
            # ----------------------
            val = 40 ## GET PROPERTY ##
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Observingconditions.Timesincelastupdate failed', ex)).json

